import type { NewsSourceAdapterMeta } from "./newsTypes";

export const newsSourceAdapters: NewsSourceAdapterMeta[] = [
  {
    id: "blockbeats",
    name: "BlockBeats",
    sourceStatus: "live",
    categoryHint: "crypto",
    requiresBackend: true,
    cadence: "hourly",
  },
  {
    id: "jinshi",
    name: "Jinshi Data",
    sourceStatus: "backend-required",
    categoryHint: "macro",
    requiresBackend: true,
    cadence: "realtime",
  },
  {
    id: "odaily",
    name: "Odaily",
    sourceStatus: "live",
    categoryHint: "crypto",
    requiresBackend: true,
    cadence: "hourly",
  },
  {
    id: "investing-cn",
    name: "Investing.com 中文",
    sourceStatus: "live",
    categoryHint: "crypto",
    requiresBackend: true,
    cadence: "hourly",
  },
  {
    id: "sina-finance",
    name: "Sina Finance",
    sourceStatus: "planned",
    categoryHint: "macro",
    requiresBackend: true,
    cadence: "planned",
  },
  {
    id: "htx-announcements",
    name: "HTX Official Announcements",
    sourceStatus: "backend-required",
    categoryHint: "htx",
    requiresBackend: true,
    cadence: "hourly",
  },
  {
    id: "wublockchain",
    name: "WuBlockchain",
    sourceStatus: "live",
    categoryHint: "crypto",
    requiresBackend: true,
    cadence: "planned",
  },
  {
    id: "coindesk",
    name: "CoinDesk",
    sourceStatus: "planned",
    categoryHint: "crypto",
    requiresBackend: true,
    cadence: "planned",
  },
  {
    id: "cointelegraph",
    name: "Cointelegraph",
    sourceStatus: "live",
    categoryHint: "crypto",
    requiresBackend: true,
    cadence: "planned",
  },
  {
    id: "the-block",
    name: "The Block",
    sourceStatus: "live",
    categoryHint: "funding",
    requiresBackend: true,
    cadence: "hourly",
  },
  {
    id: "official-macro",
    name: "Official Macro Data Sources",
    sourceStatus: "planned",
    categoryHint: "macro",
    requiresBackend: true,
    cadence: "planned",
  },
  {
    id: "onchain-alerts",
    name: "On-chain Alert Sources",
    sourceStatus: "backend-required",
    categoryHint: "onchain",
    requiresBackend: true,
    cadence: "realtime",
  },
];
